name: Snapshot update

run-name: Update application snapshot version ${{ github.event_name == 'workflow_dispatch' && '[manual]' || '' }}

on:
  schedule:
    - cron: "*/20 * * * *"

  workflow_dispatch:
    inputs:
      descriptor_build_offset:
        description: 'Offset to apply to application artifact version'
        required: false
        type: string
        default: '100100000000000'
      rely_on_FAR:
        description: 'Whether to rely on FAR for application descriptor dependencies'
        required: false
        type: boolean
        default: false
      dry_run:
        description: 'Perform dry run without making changes'
        required: false
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  update-snapshot:
    name: Update Snapshot
    uses: folio-org/kitfox-github/.github/workflows/snapshot-update.yml@master
    with:
      app_name: ${{ github.event.repository.name }}
      repo: ${{ github.repository }}
      descriptor_build_offset: ${{ github.event_name == 'workflow_dispatch' && inputs.descriptor_build_offset || '100100000000000' }}
      rely_on_FAR: ${{ github.event_name == 'workflow_dispatch' && inputs.rely_on_FAR || false }}
      dry_run: ${{ github.event_name == 'workflow_dispatch' && inputs.dry_run || false }}
    secrets: inherit